### ISSUE TITLE
Error when using classPatterns

### ISSUE THREAD

**Issue by thamacher** [vojtechhabarta/typescript-generator#61] opened 2016-05-02 12:51 UTC
As soon as I ad the "classPatterns" into the configuration the following error appears - even if I leave it empty:

io.github.lukehutch.fastclasspathscanner.classgraph.StandardClassDAGNode cannot be cast to io.github.lukehutch.fastclasspathscanner.classgraph.InterfaceDAGNode

generateTypeScript {
  outputFile = 'api.d.ts'
  outputKind = 'ambientModule'
  module = 'api'
  classPatterns = [
  ]
  classes = [
    'com.myDomain.FEAccountInfo'
  ]
  excludeClasses = [
  ]
  references = [
    'references/references.ts'
  ]
  customMappings = [
    'org.joda.money.Money:IMoney',
    'org.joda.time.DateTime:Date',
    'java.time.ZonedDateTime:Date'
  ]
  jsonLibrary = 'jackson2'
  addTypeNamePrefix = 'I'
  removeTypeNamePrefix = 'FE'
  mapDate = 'asDate'
  sortDeclarations = 'yes'
  sortTypeDeclarations = 'yes'
  noFileComment = 'yes'
}

**Comment by vojtechhabarta** [comment] 2016-05-02 13:16
It is some internal error in fast-classpath-scanner library which is used for searching for classes. Similar issue was reported but should be fixed: lukehutch/fast-classpath-scanner/issues/38.

Could you please try to narrow the problem to problematic classes/interfaces/annotations?

**Comment by vojtechhabarta** [comment] 2016-05-02 13:24
Which version of Java are you using?
Can you add whole typescript-generator output and exception stacktrace?

**Comment by thamacher** [comment] 2016-05-02 14:20
I am running it through gradle. Any chance to configure the output and stacktrace anywhere?

**Comment by vojtechhabarta** [comment] 2016-05-02 17:09
Have you tried `--full-stacktrace`?
If you could send me your sources via email I would investigate it.
If that is not possible try to divide your project in halves recursively until you find problematic classes 😄

**Comment by vojtechhabarta** [comment] 2016-05-02 17:13
BTW is it standard Java application or Android application?

**Comment by thamacher** [comment] 2016-05-02 20:40
Plain Java.

**Comment by thamacher** [comment] 2016-06-09 14:29
Any further process on this issue?
It is hard to track it down from my side, as it also happens, if I use an empty or nonsense classPattern (such as 'foo.**').

But here comes the stacktrace:

`Running TypeScriptGenerator version 1.9.205
Scanning classpath
:generateTypeScript FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':generateTypeScript'.
> io.github.lukehutch.fastclasspathscanner.classgraph.StandardClassDAGNode cannot be cast to io.github.lukehutch.fastclasspathscanner.classgraph.InterfaceDAGNode

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':generateTypeScript'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:68)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:25)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:110)
	at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
	at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
	at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
	at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
	at org.gradle.initialization.DefaultGradleLauncher$4.run(DefaultGradleLauncher.java:154)
	at org.gradle.internal.Factories$1.create(Factories.java:22)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:52)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:151)
	at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:32)
	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:99)
	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:93)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:62)
	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:93)
	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:82)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:94)
	at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:43)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:28)
	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:81)
	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:46)
	at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:52)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:37)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
	at org.gradle.util.Swapper.swap(Swapper.java:38)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.health.DaemonHealthTracker.execute(DaemonHealthTracker.java:47)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:60)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:72)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.health.HintGCAfterBuild.execute(HintGCAfterBuild.java:41)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
	at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:246)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassCastException: io.github.lukehutch.fastclasspathscanner.classgraph.StandardClassDAGNode cannot be cast to io.github.lukehutch.fastclasspathscanner.classgraph.InterfaceDAGNode
	at io.github.lukehutch.fastclasspathscanner.classgraph.StandardClassDAGNode.connect(StandardClassDAGNode.java:75)
	at io.github.lukehutch.fastclasspathscanner.classgraph.ClassGraphBuilder.<init>(ClassGraphBuilder.java:144)
	at io.github.lukehutch.fastclasspathscanner.FastClasspathScanner.scan(FastClasspathScanner.java:1422)
	at cz.habarta.typescript.generator.Input.fromClassNamePatterns(Input.java:51)
	at cz.habarta.typescript.generator.Input.fromClassNamesAndJaxrsApplication(Input.java:75)
	at cz.habarta.typescript.generator.gradle.GenerateTask.generate(GenerateTask.java:103)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:228)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:221)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:210)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:585)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:568)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
	... 71 more


BUILD FAILED
`

**Comment by vojtechhabarta** [comment] 2016-06-09 19:53
I updated `fast-classpath-scanner` library to version `1.9.19`. Can you build typescript-generator from sources (or download build from https://ci.appveyor.com/project/vojtechhabarta/typescript-generator/build/1.9.211/artifacts) and try it?

**Comment by thamacher** [comment] 2016-06-10 08:45
Yes, that works a lot better, now!
Thank you for that.

BTW:
now I get some warnings like:
Warning: Unknown serializer 'com.fasterxml.jackson.databind.ser.impl.UnknownSerializer' for class 'interface java.lang.Comparable'

does it make sense to exlude standard-java-interfaces such as Comparable, Serializable, etc?

**Comment by thamacher** [comment] 2016-06-10 09:04
Would you cut a release for that? I think, this is a major enhancement (and I won't have to use a local version ;-)!

**Comment by vojtechhabarta** [comment] 2016-06-10 09:47
It's good to hear that new `fast-classpath-scanner` version fixes your problem because I wasn't able to reproduce it.

And yes, if your JSON classes implement some interfaces which you don't want to have in generated declaration file you can exclude them.

Thanks for feedback, I will make release soon.

**Comment by vojtechhabarta** [comment] 2016-06-10 15:33
Part of [1.10.212 release](https://github.com/vojtechhabarta/typescript-generator/releases/tag/v1.10.212).

**Closed by vojtechhabarta** 2016-06-10 15:33 UTC
