### ISSUE TITLE
After update to 2.27 fails to generate due to constructor

### ISSUE THREAD

**Issue by mduft** [vojtechhabarta/typescript-generator#599] opened 2020-12-17 10:18 UTC
I have updated the generator
```
-        classpath 'cz.habarta.typescript-generator:typescript-generator-gradle-plugin:2.26.723'
+        classpath 'cz.habarta.typescript-generator:typescript-generator-gradle-plugin:2.27.744'
```
Now I'm receiving an error when generating DTOs:
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':ui:genDtos'.
> Unexpected member 'java.lang.reflect.Constructor' in property 'sorter' in class 'io.bdeploy.interfaces.plugin.PluginInfoDto'
```
The `PluginInfoDto` has a member of type `CustomProductVersionSorter` named `sorter` - which is the property causing the failure. This field is marked with `@JsonIgnore` like so:
```
public class PluginInfoDto {
...
    @JsonIgnore
    public CustomProductVersionSorter sorter;
...
}
```
This works with the older version, so for now I'm sticking with it :)

**Comment by kevincmanning** [comment] 2020-12-17 15:31
I also got this error, and have committed some changes that fixes it locally for me. In my case, it was caused by Jackson having inconsistent names for the serializable properties and the deserializable properties.

@vojtechhabarta Please see my PR and adjust accordingly as needed or advise on best way to fix this

https://github.com/vojtechhabarta/typescript-generator/pull/602

I added a //TODO because it seems that in the event that the code is designed to add any deserializable properties to the list if they don't exist in the serializable properties list. It seems in my case it was yielding CreatorProperty which was yielding Constructor rather than Field or Method. My instinct is if that is the case, just ignore it and keep processing, but please advise.

**Comment by vojtechhabarta** [comment] 2020-12-28 10:32
@mduft, @kevincmanning thanks for reporting this problem and proposing fix.

In b2e11b1eaa2817b6fe794b230691e056fc538c52 I implemented support for `@JsonCreator` used on both constructors and factory methods (see tests).
At the same time I changed handling of unsupported cases so instead of throwing an exception it is just logged.
Could you please try it?

**Comment by vojtechhabarta** [comment] 2021-01-02 11:48
Released in [v2.28.785](https://github.com/vojtechhabarta/typescript-generator/releases/tag/v2.28.785).

**Comment by mduft** [comment] 2021-01-11 06:47
Hey @vojtechhabarta - I still was on holydays :) I now tried it and it seems to work like a charm, thanks!

**Comment by vojtechhabarta** [comment] 2021-01-11 06:53
Thanks

**Closed by vojtechhabarta** 2021-01-11 06:53 UTC
