### ISSUE TITLE
TypeScript version in generated package.json

### ISSUE THREAD

**Issue by krzs** [vojtechhabarta/typescript-generator#401] opened 2019-08-06 10:42 UTC
The plugin has hardcoded version of TypeScript (^2.4) for the produced `package.json`. What do you think of upgrading it to 3.x or alternatively adding configuration parameter to set the version manually?

I use the generated code in Yarn Workspace and if other project uses declaration files with some features from TypeScript 3 (for instance, Jest library) the NPM building process fails during library checking. The solution for this is adding `--skipLibCheck` to `npmBuildScript` configuration, however in general I wouldn't consider that as a good idea.

The other thing is that the generator does not produce the lock file (`package-lock.json` or `yarn.lock`), so the TypeScript version may vary from build to build, because it's declared with caret (^2.4). So in pessimistic scenario it may happen that the same code will not compile because of a newer version of TypeScript.

**Comment by vojtechhabarta** [comment] 2019-08-06 17:50
TypeScript version is set to `^2.4` because generated code should be compilable with TypeScript 2.4 or newer. Unfortunately this doesn't allow version 3.x but it should not be a problem because it is used just to compile generated code.

I think TypeScript could be upgraded to 3.x to fix your issue but first I wanted to know what exactly the problem is. 

After some investigation we were able to identify the problem. By default TypeScript includes packages from all `node_modules/@types` above project directory. This behavior can be changed using `--typeRoots` option. It is described in [@types, typeRoots and types](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html#types-typeroots-and-types) section in TypeScript documentation.

@krzs could you please confirm that adding `--typeRoots` option (without any value) to `build` script fixes this problem?

**Comment by krzs** [comment] 2019-08-08 06:19
If I add `--typeRoots` without any value to `<npmBuildScript>` I get:
`error TS6044: Compiler option 'typeRoots' expects an argument`
However, even if it worked wouldn't it just be the same as `--skipLibCheck`?

**Comment by vojtechhabarta** [comment] 2019-08-08 09:42
You can put `--typeRoots` option before another `--` option for example like this:

`tsc --module umd --moduleResolution node --typeRoots --target es5 --lib es6 --declaration --sourceMap $outputFile`

See also comment from TypeScript project: https://github.com/Microsoft/TypeScript/issues/18581#issuecomment-330700612.

Regarding `--typeRoots` and `--skipLibCheck` difference: `--typeRoots` prevents loading unneeded files while `--skipLibCheck` just prevents checking those files. I would say that `--typeRoots` is correct in this case. You can also try `--traceResolution` option to see what is happening.

**Comment by vojtechhabarta** [comment] 2019-08-20 07:11
I plan to add `--typeRoots` option to default `build` script, could you please try it and confirm that it solves your problem?

**Comment by krzs** [comment] 2019-09-11 09:44
Yes, I confirm that adding `--typeRoots` option before another `--` option works and thus solves the problem. Thanks!

**Comment by vojtechhabarta** [comment] 2019-09-19 08:31
Released in version [2.17.558](https://github.com/vojtechhabarta/typescript-generator/releases/tag/v2.17.558).

**Closed by vojtechhabarta** 2019-09-19 08:31 UTC
