### ISSUE TITLE
Bug with implemented interfaces

### ISSUE THREAD

**Issue by ryan10132** [vojtechhabarta/typescript-generator#51] opened 2016-04-15 17:27 UTC
See https://github.com/vojtechhabarta/typescript-generator/pull/50

Interestingly, the generated `IA` interface has the x property on it, so you might think it's ok to not generate the parent interface `IB`, but it's note quite, because it's at least missing the `type` property

**Comment by vojtechhabarta** [comment] 2016-04-16 14:50
Thanks for the test.
Closing this issues as it is duplicate of #36.

**Closed by vojtechhabarta** 2016-04-16 14:50 UTC
