### ISSUE TITLE
Gradle-plugin: extensionsWithConfiguration

### ISSUE THREAD

**Issue by AMilassin** [vojtechhabarta/typescript-generator#450] opened 2020-01-24 11:33 UTC
I was trying to configure Typescript-Generator via the Gradle plugin using the `extensionsWithConfiguration` property. How to do this? My approach failed with a ClassCastException:

```
Caused by: java.lang.ClassCastException: class cz.habarta.typescript.generator.Settings$ConfiguredExtension cannot be cast to class cz.habarta.typescript.generator.Settings$ConfiguredExtension (cz.habarta.typescript.generator.Settings$ConfiguredExtension is in unnamed module of loader org.gradle.internal.classloader.VisitableURLClassLoader @201dc1be; cz.habarta.typescript.generator.Settings$ConfiguredExtension is in unnamed module of loader org.gradle.internal.classloader.VisitableURLClassLoader @1d1ef450)
        at cz.habarta.typescript.generator.Settings.loadExtensions(Settings.java:204)
        at cz.habarta.typescript.generator.gradle.GenerateTask.generate(GenerateTask.java:196)
```

`build.gradle` example
```
    def tsExtension = configure(new cz.habarta.typescript.generator.Settings.ConfiguredExtension()) {
        className = 'CustomExtension'
        configuration = ['TEST': 'test']
    }
    extensionsWithConfiguration = [
            tsExtension
    ]
```

Am I using the DSL incorrectly here?

**Comment by vojtechhabarta** [comment] 2021-01-26 21:15
I think your example is correct. Following sample is slightly simpler and should do the same:
``` gradle
    extensionsWithConfiguration = [
        new cz.habarta.typescript.generator.Settings.ConfiguredExtension(
            className: 'CustomExtension',
            configuration: ['TEST': 'test'],
        )
    ]
```

But I wasn't able to reproduce the error. I tried 1. plugin bundled in typescript-generator, 2. plugin in separate project and 3. plugin in the same project as typescript-generator was run. And I tried those cases with Gradle version 4 and 6.

The exception says that `ConfiguredExtension` class was loaded by two different class loaders so it must be some more complex build setup.

I will close the issue since it is too old but feel free to comment anyway.

**Closed by vojtechhabarta** 2021-01-26 21:15 UTC
Labels: Gradle, question
